extends Node

var question_pool = []
var pool_size = 5

var quiz_dict = {
	"Object":{
		"Definition": "Base class for all other classes in the engine.",
		"Category": "none",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AudioServer":{
		"Definition": "Server interface for low-level audio access.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CameraServer":{
		"Definition": "Server keeping track of different cameras accessible in Godot.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ClassDB":{
		"Definition": "Class information repository.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"DisplayServer":{
		"Definition": "Singleton for window management functions.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorFileSystemDirectory":{
		"Definition": "A directory for the resource filesystem.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorPaths":{
		"Definition": "Editor-only singleton that returns paths to various OS-specific data folders and files.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorSelection":{
		"Definition": "Manages the SceneTree selection in the editor.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorUndoRedoManager":{
		"Definition": "Manages undo history of scenes opened in the editor.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorVCSInterface":{
		"Definition": "Version Control System (VCS) interface, which reads and writes to the local VCS in use.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Engine":{
		"Definition": "Access to engine properties.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EngineDebugger":{
		"Definition": "Exposes the internal debugger.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GDExtensionManager":{
		"Definition": "Manages getting, loading, reloading, and unloading extensions.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Geometry2D":{
		"Definition": "Helper node for calculate generic geometry operations in 2D space.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Geometry3D":{
		"Definition": "Helper node to calculate generic geometry operations in 3D space.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GodotSharp":{
		"Definition": "Bridge between Godot and the Mono runtime (Mono-enabled builds only).",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Input":{
		"Definition": "A singleton that deals with inputs.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"InputMap":{
		"Definition": "Singleton that manages InputEventAction.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"IP":{
		"Definition": "Internet protocol (IP) support functions such as DNS resolution.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"JavaClassWrapper":{
		"Definition": "Wrapper for JavaClass.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"JavaScriptBridge":{
		"Definition": "Singleton that connects the engine with the browser's JavaScript context in Web export.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"JNISingleton":{
		"Definition": "Singleton that connects the engine with Android plugins to interface with native Android code.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"JSONRPC":{
		"Definition": "A helper to handle dictionaries which look like JSONRPC documents.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MainLoop":{
		"Definition": "Abstract base class for the game's main loop.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"SceneTree":{
		"Definition": "Manages the game loop via a hierarchy of nodes.",
		"Category": "MainLoop",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Marshalls":{
		"Definition": "Data transformation (marshaling) and encoding helpers.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MovieWriter":{
		"Definition": "Abstract class for non-real-time video recording encoders.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationMeshGenerator":{
		"Definition": "Helper class for creating and clearing navigation meshes.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationServer2D":{
		"Definition": "Server interface for low-level 2D navigation access.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationServer3D":{
		"Definition": "Server interface for low-level 3D navigation access.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Node":{
		"Definition": "Base class for all scene objects.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AnimationPlayer":{
		"Definition": "Player of Animation resources.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AnimationTree":{
		"Definition": "A node to be used for advanced animation transitions in an AnimationPlayer.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AudioStreamPlayer":{
		"Definition": "Plays back audio non-positionally.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CanvasItem":{
		"Definition": "Base class of anything 2D.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Control":{
		"Definition": "All user interface nodes inherit from this class. Its anchors and offsets adapt its position and size relative to its parent.",
		"Category": "CanvasItem",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"BaseButton":{
		"Definition": "Base class for different kinds of buttons.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Button":{
		"Definition": "Standard themed Button.",
		"Category": "BaseButton",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CheckBox":{
		"Definition": "Binary choice user interface widget.",
		"Category": "Button",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CheckButton":{
		"Definition": "Checkable button.",
		"Category": "Button",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ColorPickerButton":{
		"Definition": "Button that pops out a ColorPicker.",
		"Category": "Button",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MenuButton":{
		"Definition": "Special button that brings up a PopupMenu when clicked.",
		"Category": "Button",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"OptionButton":{
		"Definition": "Button control that provides selectable options when pressed.",
		"Category": "Button",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"LinkButton":{
		"Definition": "Simple button used to represent a link to some resource.",
		"Category": "BaseButton",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TextureButton":{
		"Definition": "Texture-based button. Supports Pressed, Hover, Disabled and Focused states.",
		"Category": "BaseButton",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ColorRect":{
		"Definition": "Displays a rectangle filled with a solid color. If you need to display the border alone, consider using ReferenceRect instead.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Container":{
		"Definition": "Base node for containers.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AspectRatioContainer":{
		"Definition": "Container that preserves its child controls' aspect ratio.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"BoxContainer":{
		"Definition": "Base class for box containers.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"HBoxContainer":{
		"Definition": "Horizontal box container.",
		"Category": "BoxContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorResourcePicker":{
		"Definition": "Godot editor's control for selecting Resource type properties.",
		"Category": "HBoxContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorScriptPicker":{
		"Definition": "Godot editor's control for selecting the script property of a Node.",
		"Category": "EditorResourcePicker",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VBoxContainer":{
		"Definition": "Vertical box container.",
		"Category": "BoxContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ColorPicker":{
		"Definition": "Color picker control.",
		"Category": "VBoxContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"FileSystemDock":{
		"Definition": " File System Dock.",
		"Category": "VBoxContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ScriptEditorBase":{
		"Definition": "Base editor for editing scripts in the ScriptEditor.",
		"Category": "VBoxContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CenterContainer":{
		"Definition": "Keeps children controls centered.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorProperty":{
		"Definition": "Custom control to edit properties for adding into the inspector.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"FlowContainer":{
		"Definition": "Base class for flow containers.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"HFlowContainer":{
		"Definition": "Horizontal flow container.",
		"Category": "FlowContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VFlowContainer":{
		"Definition": "Vertical flow container.",
		"Category": "FlowContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GraphNode":{
		"Definition": "A Container control that represents a single data unit in a GraphEdit graph. You can customize the number, type, and color of left- and right-side connection ports.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GridContainer":{
		"Definition": "Grid container used to arrange Control-derived children in a grid like layout.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MarginContainer":{
		"Definition": "Adds a top, left, bottom, and right margin to all Control nodes that are direct children of the container.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PanelContainer":{
		"Definition": " This container fits controls inside of the delimited area of a stylebox. It's useful for giving controls an outline.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ScrollContainer":{
		"Definition": "A helper node for displaying scrollable elements such as lists.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"SplitContainer":{
		"Definition": "Container for splitting and adjusting.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"HSplitContainer":{
		"Definition": "Horizontal split container. Goes from left to right.",
		"Category": "SplitContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VSplitContainer":{
		"Definition": "Vertical split container. Goes from top to bottom.",
		"Category": "SplitContainer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"SubViewportContainer":{
		"Definition": "A Container node that holds a SubViewport. It uses the SubViewport's size as minimum size, unless stretch is enabled.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TabContainer":{
		"Definition": "Arranges Control children into a tabbed view, creating a tab for each one. Only the active tab's corresponding Control has its visible property set to true.",
		"Category": "Container",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GraphEdit":{
		"Definition": "A control responsible for displaying and manipulating graph-like data using GraphNodes. It provides access to creation, removal, connection, and disconnection of nodes.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ItemList":{
		"Definition": "Control that provides a list of selectable items (and/or icons) in a single column, or optionally in multiple columns.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Label":{
		"Definition": "Displays plain text in a line or wrapped inside a rectangle. For formatted text, use RichTextLabel.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"LineEdit":{
		"Definition": "Control that provides single-line string editing.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MenuBar":{
		"Definition": "A horizontal menu bar, which displays PopupMenus or system global menu. New items can be created by adding PopupMenu nodes to this node.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NinePatchRect":{
		"Definition": "Scalable texture-based frame that tiles the texture's centers and sides, but keeps the corners' original size. Perfect for panels and dialog boxes.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Panel":{
		"Definition": "Provides an opaque background for Control children.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Range":{
		"Definition": "A base class for Control nodes that change a floating-point value between a min_value and max_value, using a configured step and page size. ",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ReferenceRect":{
		"Definition": "A rectangle box that displays only a border_color border color around its rectangle. It has no fill Color.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RichTextLabel":{
		"Definition": "Can contain custom text, fonts, images and some basic formatting. The label manages these as an internal tag stack. It also adapts itself to given width/heights.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Seperator":{
		"Definition": "Base class for separators. It is a Control used for separating other controls. It's purely a visual decoration.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"HSeperator":{
		"Definition": "Even though it looks horizontal, it is used to separate objects vertically.",
		"Category": "Seperator",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VSeparator":{
		"Definition": "Even though it looks vertical, it is used to separate objects horizontally.",
		"Category": "Seperator",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TabBar":{
		"Definition": "Simple tabs control, similar to TabContainer but is only in charge of drawing tabs, not interacting with children.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TextEdit":{
		"Definition": "Meant for editing large, multiline text. It also has facilities for editing code, such as syntax highlighting support and multiple levels of undo/redo.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TextureRect":{
		"Definition": "Used to draw icons and sprites in a user interface. The texture's placement can be controlled with the stretch_mode property. It can scale, tile, or stay centered.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Tree":{
		"Definition": "Shows branching items that can be selected, expanded and collapsed. It can have multiple columns with custom controls like text editing, buttons and popups.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VideoStreamPlayer":{
		"Definition": "Control node for playing streams using VideoStream resources. Supported formats are Ogg Theora (.ogv, VideoStreamTheora) and formats exposed via a GDExtension plugin.",
		"Category": "Control",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Node2D":{
		"Definition": "A 2D game object, with a transform (position, rotation, and scale). Use Node2D as a parent node to move, scale and rotate children. Also gives control of the node's render order.",
		"Category": "CanvasItem",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AnimatedSprite2D":{
		"Definition": "Sprite node that contains multiple textures as frames to play for animation.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AudioListener2D":{
		"Definition": "Once added to the scene tree and enabled using make_current, this node will override the location sounds are heard from. Only one can be current.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AudioStreamPlayer2D":{
		"Definition": "Plays positional sound in 2D space that is attenuated with distance to the listener. Call make_current to enable.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"BackBufferCopy":{
		"Definition": "Copies a region of the screen (or the whole screen) to a buffer so it can be accessed in your shader scripts using the screen texture.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Bone2D":{
		"Definition": "Joint used with Skeleton2D to control and animate other nodes.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Camera2D":{
		"Definition": "Forces the screen (current layer) to scroll following this node. This makes it easier (and faster) to program scrollable scenes than manually changing the position of CanvasItem-based nodes.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CanvasGroup":{
		"Definition": "Merges several child CanvasItems into a single draw operation.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CanvasModulate":{
		"Definition": "Tints the canvas elements using its assigned color.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CollisionObject2D":{
		"Definition": "The base class for 2D physics objects. It holds 2D collision Shape2Ds, assigned to a shape owner. It can have any number of shape owners, only accessible through code.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Area2D":{
		"Definition": "2D area that detects CollisionObject2D nodes overlapping, entering, or exiting. Can also alter or override local physics parameters (gravity, damping) and route audio to custom audio buses.",
		"Category": "CollisionObject2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsBody2D":{
		"Definition": "an abstract base class for implementing a physics body. All *Body2D types inherit from it.",
		"Category": "CollisionObject2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CharacterBody2D":{
		"Definition": "Specialized 2D physics body node for characters moved by script.",
		"Category": "PhysicsBody2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RigidBody2D":{
		"Definition": "Physics Body which is moved by 2D physics simulation. Useful for objects that have gravity and can be pushed by other objects.",
		"Category": "PhysicsBody2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"StaticBody2D":{
		"Definition": "Physics body for 2D physics which is static or moves only by script. Useful for floor and walls.",
		"Category": "PhysicsBody2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AnimatableBody2D":{
		"Definition": "Animatable body for 2D physics. An animatable body can't be moved by external forces or contacts, but can be moved by script or animation to affect other bodies in its path.",
		"Category": "StaticBody2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CollisionPolygon2D":{
		"Definition": "Provides a concave or convex 2D collision polygon to a CollisionObject2D parent. Polygons can be drawn in the editor or specified by a list of vertices. See also ConvexPolygonShape2D.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CollisionShape2D":{
		"Definition": "Editor facility for creating and editing collision shapes in 2D space. Set the shape property to configure the shape. Use CollisionObject2D.shape_owner_get_shape to get the actual shape.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CPUParticles2D":{
		"Definition": "CPU-based 2D particle node used to create a variety of particle systems and effects. More compatibility than GPU-based but without hardware acceleration.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GPUParticles2D":{
		"Definition": "GPU-based 2D particle node used to create a variety of particle systems and effects. It features an emitter that generates some number of particles at a given rate.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Joint2D":{
		"Definition": "Base node for all joint constraints in 2D physics. Joints take 2 bodies and apply a custom constraint.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"DampedSpringJoint2D":{
		"Definition": "Constraint for 2D physics which always wants to go back to a given length.",
		"Category": "Joint2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GrooveJoint2D":{
		"Definition": "Constraint for 2D physics which is useful for making a body 'slide' through a segment placed in another.",
		"Category": "Joint2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PinJoint2D":{
		"Definition": "Type of joint for 2D rigid bodies. It attaches two bodies (dynamic or static) together.",
		"Category": "Joint2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Light2D":{
		"Definition": "Casts light in a 2D environment. A light is defined as a color, an energy value, a mode (see constants), and various other parameters (range and shadows-related).",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"DirectionalLight2D":{
		"Definition": "Models an infinite number of parallel rays covering the entire scene. It is used for distant lights with strong intensity (for example: to model sunlight or moonlight).",
		"Category": "Light2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PointLight2D":{
		"Definition": "Casts light in a 2D environment. This light's shape is defined by a (usually grayscale) texture.",
		"Category": "Light2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"LightOccluder2D":{
		"Definition": "Occludes light cast by a Light2D, casting shadows. It must be provided with an OccluderPolygon2D in order for the shadow to be computed.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Line2D":{
		"Definition": "A line through several points in 2D space.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Marker2D":{
		"Definition": "Generic 2D position hint for a plain Node2D that displays a cross in the 2D editor at all times. You can set cross' visual size by using the gizmo in the 2D editor while the node is selected.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MeshInstance2D":{
		"Definition": "Node used for displaying a Mesh in 2D. This can be automatically created from an existing Sprite2D via a tool in the editor toolbar.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MultiMeshInstance2D":{
		"Definition": "A specialized node to instance a MultiMesh resource in 2D. Usage is the same as its 3D counterpart.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationLink2D":{
		"Definition": "Creates a link between two positions that NavigationServer2D can route agents through. Links can be used to navigate off the navigation mesh, like teleporters or jumping across gaps.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationRegion2D":{
		"Definition": "A region of the navigation map. It tells the NavigationServer2D what can be navigated and what cannot, based on its NavigationPolygon resource.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ParallaxLayer":{
		"Definition": "Each of these layers can be set to move at different speeds relative to the camera movement or the ParallaxBackground.scroll_offset value. Must be the child of a ParallaxBackground node.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Path2D":{
		"Definition": "Can have PathFollow2D child nodes moving along the Curve2D. The path is considered as relative to the moved nodes. As such, the curve should usually start with a zero vector ((0, 0)).",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PathFollow2D":{
		"Definition": "This node takes its parent Path2D and returns the coordinates of a point within it, given a distance from the first vertex. It is useful for easily making other nodes follow a path.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Polygon2D":{
		"Definition": "Defined by a set of points. Each point is connected to the next, with the final point being connected to the first, resulting in a closed shape. Can be filled with color/texture.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RayCast2D":{
		"Definition": "Represents a line from its origin to its destination position, target_position. It is used to query the 2D space in order to find the closest object along the path of the ray.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RemoteTransform2D":{
		"Definition": "Pushes its own Transform2D to another Node2D derived node (called the remote node) in the scene. It can use either global or local coordinates.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ShapeCast2D":{
		"Definition": "Node for physics collision sweep and immediate overlap queries. Similar to the RayCast2D node.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Skeleton2D":{
		"Definition": "Parents a hierarchy of Bone2D objects. It is a requirement of Bone2D. It holds a reference to the rest pose of its children and acts as a single point of access to its bones.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Sprite2D":{
		"Definition": "A node that displays a 2D texture. The texture displayed can be a region from a larger atlas texture, or a frame from a sprite sheet animation.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TileMap":{
		"Definition": "Node for 2D tile-based maps. It uses a TileSet which contains a list of tiles which are used to create grid-based maps. It may have several layers, layouting tiles on top of each other.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TouchScreenButton":{
		"Definition": "Allows you to create on-screen buttons for touch devices. It's intended for gameplay use, such as a unit you have to touch to move. ",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VisibleOnScreenNotifier2D":{
		"Definition": "Detects when it is visible on the screen. It also notifies when its bounding rectangle enters or exits the screen or a viewport.",
		"Category": "Node2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VisibleOnScreenEnabler2D":{
		"Definition": "Detects when it is visible on screen (just like its parent) and automatically enables or disables the target node. The target node is reenabled with this is on screen.",
		"Category": "VisibleOnScreenNotifier2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CanvasLayer":{
		"Definition": "Canvas drawing layer. CanvasItem nodes that are direct or indirect children of a CanvasLayer will be drawn in that layer. The layer is a numeric index that defines the draw order.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ParallaxBackground":{
		"Definition": "Uses one or more ParallaxLayer child nodes to create a parallax effect. Each can move at a different speed using ParallaxLayer.motion_offset. ",
		"Category": "CanvasLayer",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorFileSystem":{
		"Definition": "This object holds information of all resources in the filesystem, their types, etc. Note: This class shouldn't be instantiated directly, rather use EditorInterface.get_resource_filesystem.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorInterface":{
		"Definition": " Gives you control over Godot editor's window. Note: This class shouldn't be instantiated directly. Instead, access the singleton using EditorPlugin.get_editor_interface.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorPlugin":{
		"Definition": "Plugins are used by the editor to extend functionality. The most common types of plugins are those which edit a given node or resource type, import plugins and export plugins.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"EditorResourcePreview":{
		"Definition": "This object is used to generate previews for resources of files. Note: This class shouldn't be instantiated directly. Rather, use EditorInterface.get_resource_previewer.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"HTTPRequest":{
		"Definition": "A node with the ability to send HTTP requests. Uses HTTPClient internally. Can be used to make HTTP requests, i.e. download or upload files or web content via HTTP.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"InstancePlaceholder":{
		"Definition": "Turning on the option Load As Placeholder for an instantiated scene in the editor causes it to be replaced by this when running the game. This will not replace the node in the editor. ",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MissingNode":{
		"Definition": "This is an internal editor class intended for keeping data of nodes of unknown type (most likely this type was supplied by an extension that is no longer loaded).",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MultiplayerSpawner":{
		"Definition": "Automatically replicates spawnable nodes from the authority to other multiplayer peers. Spawnable scenes can be configured in the editor or through code (see add_spawnable_scene).",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"MultiplayerSynchronizer":{
		"Definition": "Synchronizes properties from the multiplayer authority to the remote peers. By default, it synchronizes configured properties to all peers.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationAgent2D":{
		"Definition": "2D Agent that is used in navigation to reach a position while avoiding static and dynamic obstacles. The dynamic obstacles are avoided using RVO collision avoidance. ",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationAgent3D":{
		"Definition": "3D Agent that is used in navigation to reach a position while avoiding static and dynamic obstacles. The dynamic obstacles are avoided using RVO collision avoidance.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationObstacle2D":{
		"Definition": "2D Obstacle used in navigation for collision avoidance. The obstacle needs navigation data to work correctly. It is physics safe.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationObstacle3D":{
		"Definition": "3D Obstacle used in navigation for collision avoidance. The obstacle needs navigation data to work correctly. It is physics safe.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Node3D":{
		"Definition": "Most basic 3D game object, parent of all 3D-related nodes.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AudioListener3D":{
		"Definition": "Added to the scene tree and enabled using make_current, this node overrides the location of sounds. This can be used to listen from a location different from the Camera3D.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AudioStreamPlayer3D":{
		"Definition": "Added to the scene tree and enabled using make_current, this node overrides the location of sounds. This can be used to listen from a location different from the Camera3D.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"BoneAttachment3D":{
		"Definition": "This node will allow you to select a bone for this node to attach to. It can copy the transform of the select bone, or can override the transform of the selected bone.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Camera3D":{
		"Definition": "A special node that displays what is visible from its current location. Cameras register themselves in the nearest Viewport node (when ascending the tree).",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CollisionObject3D":{
		"Definition": "The base class for physics objects. It can hold any number of collision Shape3Ds. Each shape must be assigned to a shape owner. It can have any number of shape owners.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Area3D":{
		"Definition": "Region that detects CollisionObject3D nodes overlapping, entering, or exiting. Can also alter or override local physics parameters (gravity, damping) and route audio to custom audio buses.",
		"Category": "CollisionObject3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsBody3D":{
		"Definition": "An abstract base class for implementing a physics body. All *Body3D types inherit from it.",
		"Category": "CollisionObject3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CharacterBody3D":{
		"Definition": "Specialized 3D physics body node for characters moved by script.",
		"Category": "PhysicsBody3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicalBone3D":{
		"Definition": "3D physical bone. Be sure to keep its scale uniform and change the size(s) of the collision shape instead.",
		"Category": "PhysicsBody3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RigidBody3D":{
		"Definition": "Physics Body which is moved by 3D physics simulation. Useful for objects that have gravity and can be pushed by other objects.",
		"Category": "PhysicsBody3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"StaticBody3D":{
		"Definition": "Physics body for 3D physics which is static or moves only by script. Useful for floor and walls.",
		"Category": "PhysicsBody3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AnimatableBody3D":{
		"Definition": "Physics body for 3D physics which moves only by script or animation. Useful for moving platforms and doors.",
		"Category": "StaticBody3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CollisionPolygon3D":{
		"Definition": "Editor-only node for defining a collision polygon in 3D space. Allows editing a concave or convex collision polygon's vertices on a selected plane. Can also set a perpendicular depth.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"CollisionShape3D":{
		"Definition": "Editor facility for creating and editing collision shapes in 3D space. Set the shape property to configure the shape. Use CollisionObject3D.shape_owner_get_shape to get the actual shape.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GridMap":{
		"Definition": "Node for 3D tile-based maps. It lets you place meshes on a grid interactively. It works both from the editor and from scripts, which can help you create in-game level editors.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ImporterMeshInstance3D":{
		"Definition": "MeshInstance3D Importer. Gets and sets meshes, skeleton paths, and skins.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Joint3D":{
		"Definition": "Base class for all 3D joints. Joints are used to bind together two physics bodies. They have a solver priority and can define if the bodies of the two attached nodes should be able to collide.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ConeTwistJoint3D":{
		"Definition": "A joint between two 3D PhysicsBodies that can rotate the bodies across an axis defined by the local x-axes of the Joint3D. The twist axis is initiated as the X axis of the Joint3D.",
		"Category": "Joint3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Generic6DOFJoint3D":{
		"Definition": "The generic 6-degrees-of-freedom joint can implement a variety of joint types by locking certain axes' rotation or translation.",
		"Category": "Joint3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"HingeJoint3D":{
		"Definition": "A hinge between two 3D PhysicsBodies. It normally uses the Z axis of body A as the hinge axis, another axis can be specified when adding it manually though.",
		"Category": "Joint3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PinJoint3D":{
		"Definition": "A joint for 3D rigid that pins 2 bodies (dynamic or static) together. See also Generic6DOFJoint3D.",
		"Category": "Joint3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"SliderJoint3D":{
		"Definition": "Slider between two PhysicsBodies in 3D. Slides across the X axis of the pivot object. See also Generic6DOFJoint3D.",
		"Category": "Joint3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"LightmapProbe":{
		"Definition": "Represents the position of a single manually placed probe for dynamic object lighting with LightmapGI.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Marker3D":{
		"Definition": "Generic 3D position hint for editing. It's just like a plain Node3D, but it displays as a cross in the 3D editor at all times.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationLink3D":{
		"Definition": "Creates a link between two positions that NavigationServer3D can route agents through. Links can be used to navigate off the navigation mesh, like teleporters or jumping across gaps.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"NavigationRegion3D":{
		"Definition": "A region of the navigation map. It tells the NavigationServer3D what can be navigated and what cannot, based on its NavigationMesh resource.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"OccluderInstance3D":{
		"Definition": "Provides occlusion culling for 3D nodes, which improves performance in closed areas. Can improve rendering performance by hiding geometry that is occluded by other objects.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"OpenXRHand":{
		"Definition": "This node enables OpenXR's hand tracking functionality. The node should be a child node of an XROrigin3D node, tracking will update its position to where the player's actual hand is positioned. ",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Path3D":{
		"Definition": "Can have PathFollow3D child nodes moving along the Curve3D. See PathFollow3D for more information on the usage.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PathFollow3D":{
		"Definition": "This node takes its parent Path3D, and returns the coordinates of a point within it, given a distance from the first vertex. It is useful for easily making other nodes follow a path. ",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RayCast3D":{
		"Definition": "Represents a line from its origin to its destination position, target_position. It is used to query the 3D space in order to find the closest object along the path of the ray.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RemoteTransform3D":{
		"Definition": "Pushes its own Transform3D to another Node3D derived Node (called the remote node) in the scene. It can be set to update another Node's position, rotation and/or scale.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ShapeCast3D":{
		"Definition": "Node for physics collision sweep and immediate overlap queries. Similar to the RayCast3D node.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Skeleton3D":{
		"Definition": "Provides a hierarchical interface for managing 3D bones, including pose, rest and animation (see Animation). It can also use ragdoll physics.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"SpringArm3D":{
		"Definition": "A helper node, mostly used in 3rd person cameras. It casts a ray (or collision shape) along its z axis and moves all its direct children to the collision point, minus a margin.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VehicleWheel3D":{
		"Definition": "Needs to be used as a child node of VehicleBody3D and simulates the behavior of one of its wheels. This node also acts as a collider to detect if the wheel is touching a surface.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VisualInstance3D":{
		"Definition": "Parent of all visual 3D nodes. It is used to connect a resource to a visual representation. You should not access its properties directly. Node representation of RenderingServer.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Decal":{
		"Definition": "Node that projects a texture onto a MeshInstance3D. Use Decals to add detail to a scene without affecting the underlying Mesh. They are often used to add weathering, dirt, and prop variety.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"FogVolume":{
		"Definition": "Used to add localized fog into the global volumetric fog effect. These can also remove volumetric fog from specific areas if using a FogMaterial with a negative FogMaterial.density.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GeometryInstance3D":{
		"Definition": "Base node for geometry-based visual instances. Shares some common functionality like visibility and custom materials.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GPUParticlesAttractor3D":{
		"Definition": "Abstract class for 3D particle attractors affecting GPUParticles3D nodes. They can be used to attract particles towards them or push particles away from them.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GPUParticlesCollision3D":{
		"Definition": "Abstract class for 3D particle collision shapes affecting GPUParticles3D nodes. Particle collision shapes can be used to make particles stop or bounce against them.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GPUParticlesCollisionBox3D":{
		"Definition": "Box-shaped 3D particle collision shape affecting GPUParticles3D nodes.",
		"Category": "GPUParticlesCollision3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GPUParticlesCollisionHeightField3D":{
		"Definition": "Real-time heightmap-shaped 3D particle attractor affecting GPUParticles3D nodes. Less flexible than GPUParticlesCollisionSDF3D, but doesn't require baking.",
		"Category": "GPUParticlesCollision3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GPUParticlesCollisionSDF3D":{
		"Definition": "Baked signed distance field 3D particle attractor affecting GPUParticles3D nodes. More flexible than GPUParticlesCollisionHeightField3D, but it requires a baking step.",
		"Category": "GPUParticlesCollision3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"GPUParticlesCollisionSphere3D":{
		"Definition": "Sphere-shaped 3D particle collision shape affecting GPUParticles3D nodes.",
		"Category": "GPUParticlesCollision3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Light3D":{
		"Definition": "The abstract base class for light nodes. As it can't be instantiated, it shouldn't be used directly. Other types of light nodes inherit from it.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"DirectionalLight3D":{
		"Definition": "A type of Light3D node that models an infinite number of parallel rays covering the entire scene. It is used for distant lights with strong intensity to model sunlight or moonlight.",
		"Category": "Light3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"OmniLight3D":{
		"Definition": "A type of Light3D that emits light in all directions. The light is attenuated by distance and this attenuation can be configured by changing its energy, radius, and attenuation parameters.",
		"Category": "Light3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"SpotLight3D":{
		"Definition": "A spotlight, such as a reflector spotlight or a lantern. A type of Light3D node that emits lights in a specific direction, in the shape of a cone. ",
		"Category": "Light3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"LightmapGI":{
		"Definition": "Used to compute and store baked lightmaps. Lightmaps are used to provide high-quality indirect lighting with very little light leaking.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ReflectionProbe":{
		"Definition": "Captures its surroundings as a cubemap, and stores versions of it with increasing levels of blur to simulate different material roughnesses.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RootMotionView":{
		"Definition": "Refers to an animation technique where a mesh's skeleton is used to give impulse to a character. For example, this allows animating in a way where steps actually match the floor below.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VisibleOnScreenNotifier3D":{
		"Definition": "Detects when it is visible on the screen. It also notifies when its bounding rectangle enters or exits the screen or a Camera3D's view.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VisibleOnScreenEnabler3D":{
		"Definition": "Will disable RigidBody3D and AnimationPlayer nodes when they are not visible. It will only affect other nodes within the same scene.",
		"Category": "VisibleOnScreenNotifier3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"VoxelGI":{
		"Definition": "Real-time global illumination (GI) probe. Used to provide high-quality real-time indirect light and reflections to scenes.",
		"Category": "VisualInstance3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"XRNode3D":{
		"Definition": "This node can be bound to a specific pose of a XRPositionalTracker and will automatically have its Node3D.transform updated by the XRServer.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"XRAnchor3D":{
		"Definition": "A spatial node that maps a real world location identified by the AR platform to a position within the game world. ",
		"Category": "XRNode3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"XRController3D":{
		"Definition": "A helper spatial node that is linked to the tracking of controllers. It also offers several handy passthroughs to the state of buttons and such on the controllers.",
		"Category": "XRNode3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"XROrigin3D":{
		"Definition": "A special node within the AR/VR system that maps the physical location of the center of our tracking space to the virtual location within our game world.",
		"Category": "Node3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ResourcePreloader":{
		"Definition": "Used to preload sub-resources inside a scene, so when the scene is loaded, all the resources are ready to use and can be retrieved from the preloader.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ShaderGlobalsOverride":{
		"Definition": "Overrides shader globals.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"SkeletonIK3D":{
		"Definition": " Used to place the end bone of a Skeleton3D bone chain at a certain point in 3D by rotating all bones in the chain accordingly.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Timer":{
		"Definition": "Counts down a specified interval and emits a signal on reaching 0. Can be set to repeat or 'one-shot' mode. Note: To create a one-shot timer without instantiating a node, use SceneTree.create_timer.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Viewport":{
		"Definition": "Base class for viewports. It creates a different view into the screen, or a sub-view inside another viewport. Children 2D Nodes will display on it, and children Camera3D nodes will render on it.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"SubViewport":{
		"Definition": "Creates a sub-view into the screen. It is a Viewport that isn't a Window, i.e. it doesn't draw anything by itself.",
		"Category": "Viewport",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Window":{
		"Definition": "Base class for all windows. It creates a window. The window can either be a native system window or embedded inside another Window (see Viewport.gui_embed_subwindows).",
		"Category": "Viewport",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"AcceptDialog":{
		"Definition": "Base dialog for user notification. This dialog is useful for small notifications to the user about an event. It can only be accepted or closed, with the same result.",
		"Category": "Window",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Popup":{
		"Definition": "Popup is a base window container for popup-like subwindows. It's a modal by default (see Window.popup_window) and has helpers for custom popup behavior.",
		"Category": "Window",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PopupMenu":{
		"Definition": "A modal window used to display a list of options. They are popular in toolbars or context menus. Its size can be limited by using Window.max_size.",
		"Category": "Popup",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PopupPanel":{
		"Definition": "Class for displaying popups with a panel background. In some cases it might be simpler to use than Popup, since it provides a configurable background.",
		"Category": "Popup",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"WorldEnvironment":{
		"Definition": "Default environment properties for the entire scene (post-processing effects, lighting and background settings). It is used to configure the default Environment for the scene.",
		"Category": "Node",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"OS":{
		"Definition": "Wraps the most common functionality to communicate with the host operating system, such as the clipboard, video driver, delays, environment variables, execution of binaries, command line, etc.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Performance":{
		"Definition": "Exposes a number of different monitors related to performance, such as memory usage, draw calls, and FPS. These are the same values displayed in the Monitor tab in the Debugger panel.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsDirectBodyState2D":{
		"Definition": "Provides direct access to a physics body in the PhysicsServer2D, allowing safe changes to physics properties. This object is passed via the direct state callback of rigid bodies.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsDirectBodyState2DExtension":{
		"Definition": "Extension to PhysicsDirectBodyState2D.",
		"Category": "PhysicsDirectBodyState2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsDirectBodyState3D":{
		"Definition": "Provides direct access to a physics body in the PhysicsServer3D, allowing safe changes to physics properties. This object is passed via the direct state callback of rigid bodies.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsDirectBodyState3DExtension":{
		"Definition": "Extension to PhysicsDirectBodyState2D.",
		"Category": "PhysicsDirectBodyState3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsDirectSpaceState2D":{
		"Definition": "Direct access object to a space in the PhysicsServer2D. It's used mainly to do queries against objects and areas residing in a given space.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsDirectSpaceState2DExtension":{
		"Definition": "Extension to PhysicsDirectSpaceState2DExtension.",
		"Category": "PhysicsDirectSpaceState2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsDirectSpaceState3D":{
		"Definition": "Direct access object to a space in the PhysicsServer3D. It's used mainly to do queries against objects and areas residing in a given space.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsDirectSpaceState3DExtension":{
		"Definition": "Extension to PhysicsDirectSpaceState3D.",
		"Category": "PhysicsDirectSpaceState3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsServer2D":{
		"Definition": "Server interface for low-level 2D physics access. It is responsible for all 2D physics. It can directly create and manipulate all physics objects.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsServer2DExtension":{
		"Definition": "Extension to PhysicsServer2D.",
		"Category": "PhysicsServer2D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsServer2DManager":{
		"Definition": "The API for registering PhysicsServer2D implementations, and for setting the default implementation. This class is only used on startup at the server initialization level.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsServer3D":{
		"Definition": "Server interface for low-level 3D physics access. It is responsible for all 3D physics. It can create many kinds of physics objects, but does not insert them on the node tree.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsServer3DExtension":{
		"Definition": "Extension to PhysicsServer3D.",
		"Category": "PhysicsServer3D",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsServer3DManager":{
		"Definition": "The API for registering PhysicsServer3D implementations, and for setting the default implementation. This class is only used on startup at the server initialization level.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"PhysicsServer3DRenderingServerHandler":{
		"Definition": "Rendering server handler for 3D physics.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ProjectSettings":{
		"Definition": "Contains global variables accessible from everywhere. Use get_setting, set_setting or has_setting to access them. Very useful for reading custom game configuration options.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RefCounted":{
		"Definition": "Base class for reference-counted objects.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RefCounted children":{
		"Definition": "TOO DAMN MANY OF THEM. Use a RefCondom.",
		"Category": "RefCounted",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RenderingDevice":{
		"Definition": "Abstraction for working with modern low-level graphics APIs.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"RenderingServer":{
		"Definition": "Server for anything visible.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ResourceLoader":{
		"Definition": "Singleton used to load resource files.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ResourceSaver":{
		"Definition": "Singleton for saving Godot-specific resource types.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ResourceUID":{
		"Definition": "Singleton for managing a cache of resource UIDs within a project.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ScriptLanguage":{
		"Definition": "The scripting language.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ScriptLanguageExtension":{
		"Definition": "Extension to ScriptLanguage.",
		"Category": "ScriptLanguage",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TextServerManager":{
		"Definition": "Manager for the font and complex text layout servers.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"ThemeDB":{
		"Definition": "An engine singleton providing access to static Theme information, such as default and project theme, and fallback values.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TileData":{
		"Definition": "Settings for a single tile in a TileSet.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"Time":{
		"Definition": "Time singleton for working with time.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TranslationServer":{
		"Definition": "Server that manages all translations.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"TreeItem":{
		"Definition": "Control for a single item inside a Tree.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"UndoRedo":{
		"Definition": "Helper to manage undo/redo operations in the editor or custom tools.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"WorkerThreadPool":{
		"Definition": "Handles tasks and group tasks in worker threads.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
	"XRServer":{
		"Definition": "Server for AR and VR features.",
		"Category": "Object",
		"UserGrade": "0",
		"RepNumber": "0",
		"Easiness": "0",
		"Interval": "0",
		"LastDateAndTime": "never",
	},
}

func _ready():

	populate_question_pool(pool_size)

func populate_question_pool(pool_size):
	#put all terms in an array
	var all_terms = []	
	for key in quiz_dict.keys():
		all_terms.append(key)		
	var remaining_terms = all_terms
		
	var i = 0
	while i < pool_size:
		#TODO: WARN IF POOL SIZE IS GREATER THAN ALL TERMS SIZE
		var new_q = Question.new()
		new_q.term = remaining_terms.pop_at(randi() % remaining_terms.size())
		new_q.category = quiz_dict.get(new_q.term).get("Category")
		new_q.definition = quiz_dict.get(new_q.term).get("Definition")
		new_q.user_grade = quiz_dict.get(new_q.term).get("UserGrade")
		new_q.rep_number = quiz_dict.get(new_q.term).get("RepNumber")
		new_q.easiness = quiz_dict.get(new_q.term).get("Easiness")
		new_q.interval = quiz_dict.get(new_q.term).get("Interval")
		new_q.last_date_and_time = quiz_dict.get(new_q.term).get("LastDateAndTime")
		question_pool.append(new_q)
		
		#picking siblings as wrong answers first
		var siblings = []
		for key in quiz_dict.keys():
			if key != new_q.term:
				if new_q.category == quiz_dict.get(key).get("Category"):
					siblings.append(key)
		
		#needed if not enough siblings, just choose from all terms
		var all_terms_left = all_terms
		all_terms_left.erase(new_q.term)
		while new_q.answers.size() < 4:
			if siblings.size() != 0:
				var new_wrong_answer = siblings.pop_at(randi() % siblings.size())
				new_q.answers.append(new_wrong_answer)
				all_terms_left.erase(new_wrong_answer)
			else:
				var new_wrong_answer = all_terms_left.pop_at(randi() % all_terms_left.size())
				new_q.answers.append(new_wrong_answer)
		
		new_q.correct_answer_index = randi_range(0,3)
		new_q.answers[new_q.correct_answer_index] = new_q.term		
					
		print ("\nPool Question: " + str(i + 1))
		new_q.print_term_and_definition()
		new_q.print_answer_selection()
		
		question_pool.append(new_q)
		i += 1
	

func generateWrongAnswers():
	pass
